# Generated by Django 4.2.20 on 2025-05-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='translation',
            field=models.TextField(blank=True),
        ),
    ]
